# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc3b30b1955986845bb8d844db4d75085c36cb3bb20472a297b06de1fe78bd9232aa48ac815e9217aa024a2af71971d543eeb90dbed51ada4d0579538959b74c

test:
  secret_key_base: b792a0595c451545254a30b201490db7e4f4359099eabad84a7db6e0daf81b47247a68c9cad8275f0157d7e68ee140e9a8914bc7d354bfc24258dd2a834d7770

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
